alias: Axis Video Motion Detection 4 (Axis VMD4) Scripted Group of Actions
description: "This example uses Axis VMD4 on an Axis M3105 POE IP network camera as the primary trigger to run scripts to turn on outdoor front lights when motion is detected. This automation is based off of the following documentation: https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions"
trigger:
  - platform: state
    entity_id: binary_sensor.m3105_l_0_vmd4_camera1profileany
    from: "off"
    to: "on"
condition:
  - condition: numeric_state
    entity_id: sun.sun
    below: "-3.0"
    value_template: "{{ state.attributes.elevation }}"
action:
  - choose:
      - conditions:
          - condition: time
            after: "16:00:00"
            before: "20:59:59"
        sequence:
          - service: script.turn_on
            entity_id: script.turn_on_front
      - conditions:
          - condition: time
            after: "21:00:00"
            before: "21:59:59"
        sequence:
          - service: script.turn_on
            entity_id: script.turn_on_dim
      - conditions:
          - condition: time
            after: "22:00:00"
            before: "07:00:00"
        sequence:
          - service: script.turn_on
            entity_id: script.turn_on_sleep
    default:
      - service: script.turn_on
        entity_id: script.turn_on_sleep
  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.m3105_l_0_vmd4_camera1profileany
      from: "on"
      to: "off"
  - delay:
      minutes: "{{ range(3, 10)|random }}"
  - service: script.turn_on
    entity_id: script.turn_off_front
mode: restart
